name: Unified ML Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug Environment
      run: |
        echo "Current working directory:"
        pwd
        echo "List of files:"
        ls -R

    - name: Run tests
      run: |
        pytest data_processing/test_data_processing.py --disable-warnings
        pytest model_training/test_train_model.py
        pytest flask_api/test_app.py --disable-warnings